# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 13 Nov 2013 23:23:37 +0000
*	@ALL	0
*	@user	8
wiki:dokuwiki	@ALL	1
wiki:syntax	@ALL	1
wiki:welcome	@ALL	1
